Fix a majority of script bugs

diff --git a/pro-audio-scripts/wineasio_register b/pro-audio-scripts/wineasio_register
--- a/pro-audio-scripts/wineasio_register
+++ b/pro-audio-scripts/wineasio_register
@@ -1,13 +1,30 @@
 #!/usr/bin/bash
 
-# exit if any command fails
-set -e
-
 # Path to where YaVST winebuild resides.
-PATH_TO_WINE_BUILD="/home/artofmusic/.plugins/YaVST"
+PATH_TO_WINE_BUILD="${HOME}/.plugins/YaVST"
+
+# Wineasio binary package
+WINEASIO_PKG="wineasio-1.3.0-2-x86_64.pkg.tar.zst"
+
+# Download archive
+wget "https://builds.garudalinux.org/repos/chaotic-aur/x86_64/${WINEASIO_PKG}"
+
+# Extract archive
+tar --use-compress-program=unzstd -xvf "${PWD}/${WINEASIO_PKG}"
+
+# Move WineASIO binary
+cp -rf "${PWD}/usr/lib" "${PATH_TO_WINE_BUILD}"
+
+# Remove leftovers
+rm "${WINEASIO_PKG}"
+rm -rf "${PWD}/usr"
+rm .*
 
 # read WINEPREFIX from environment, with fallback if unset
 WINEPREFIX=${WINEPREFIX:=~/.wine}
+
+# exit if any command fails
+set -e
 
 # make sure the WINEPREFIX directory exists
 if [ ! -d "${WINEPREFIX}" ]; then
@@ -15,32 +32,12 @@ if [ ! -d "${WINEPREFIX}" ]; then
 fi
 
 # define possible locations for wineasio DLLs
-u32=(
-"${PATH_TO_WINE_BUILD}/lib/wine/i386-unix/wineasio32.dll.so"
-"${PATH_TO_WINE_BUILD}/lib32/wine/i386-unix/wineasio32.dll.so"
-"${PATH_TO_WINE_BUILD}/lib/i386-linux-gnu/wine/i386-unix/wineasio32.dll.so"
-)
 
 u64=(
 "${PATH_TO_WINE_BUILD}/lib/wine/x86_64-unix/wineasio64.dll.so"
 "${PATH_TO_WINE_BUILD}/lib64/wine/x86_64-unix/wineasio64.dll.so"
 "${PATH_TO_WINE_BUILD}/lib/x86_64-linux-gnu/wine/x86_64-unix/wineasio64.dll.so"
 )
-
-# try to register 32bit DLL
-for u in ${u32[@]}; do
-    w=$(echo ${u} | sed -e 's|/i386-unix/wineasio32.dll.so|/i386-windows/wineasio32.dll|g')
-    if [ -e "${u}" ] && [ -e "${w}" ]; then
-        cp -v "${w}" "${WINEPREFIX}/drive_c/windows/system32"
-        regsvr32 "${u}"
-        break
-    fi
-done
-
-# only continue past this point if wine64 command is available and prefix supports 64bit
-if ! command -v wine64 > /dev/null || [ ! -d "${WINEPREFIX}/drive_c/windows/syswow64" ]; then
-    exit 0
-fi
 
 # try to register 64bit DLL
 for u in ${u64[@]}; do
